2023-11-05 13:38:42,082 INFO    MainThread:47760 [wandb_setup.py:_flush():76] Current SDK version is 0.15.2
2023-11-05 13:38:42,082 INFO    MainThread:47760 [wandb_setup.py:_flush():76] Configure stats pid to 47760
2023-11-05 13:38:42,082 INFO    MainThread:47760 [wandb_setup.py:_flush():76] Loading settings from /Users/josepsmachine/.config/wandb/settings
2023-11-05 13:38:42,082 INFO    MainThread:47760 [wandb_setup.py:_flush():76] Loading settings from /Users/josepsmachine/Documents/PROGRAMMING/BioBytes_Uib_Datathon2023/wandb/settings
2023-11-05 13:38:42,082 INFO    MainThread:47760 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-11-05 13:38:42,082 INFO    MainThread:47760 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-11-05 13:38:42,083 INFO    MainThread:47760 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-11-05 13:38:42,083 INFO    MainThread:47760 [wandb_init.py:_log_setup():507] Logging user logs to /Users/josepsmachine/Documents/PROGRAMMING/BioBytes_Uib_Datathon2023/wandb/run-20231105_133842-wimtjzb1/logs/debug.log
2023-11-05 13:38:42,083 INFO    MainThread:47760 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/josepsmachine/Documents/PROGRAMMING/BioBytes_Uib_Datathon2023/wandb/run-20231105_133842-wimtjzb1/logs/debug-internal.log
2023-11-05 13:38:42,083 INFO    MainThread:47760 [wandb_init.py:_jupyter_setup():453] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x152a48520>
2023-11-05 13:38:42,084 INFO    MainThread:47760 [wandb_init.py:init():547] calling init triggers
2023-11-05 13:38:42,084 INFO    MainThread:47760 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-11-05 13:38:42,084 INFO    MainThread:47760 [wandb_init.py:init():571] re-initializing run, found existing run on stack: 4uh5xl6r
2023-11-05 13:38:42,086 INFO    MainThread:47760 [wandb_run.py:_finish():1893] finishing run haradai/datahon_uib_2023/4uh5xl6r
2023-11-05 13:38:42,086 INFO    MainThread:47760 [wandb_run.py:_atexit_cleanup():2127] got exitcode: 0
2023-11-05 13:38:42,086 INFO    MainThread:47760 [wandb_run.py:_restore():2110] restore
2023-11-05 13:38:42,087 INFO    MainThread:47760 [wandb_run.py:_restore():2116] restore done
2023-11-05 13:38:47,466 INFO    MainThread:47760 [wandb_run.py:_footer_history_summary_info():3469] rendering history
2023-11-05 13:38:47,467 INFO    MainThread:47760 [wandb_run.py:_footer_history_summary_info():3501] rendering summary
2023-11-05 13:38:47,476 INFO    MainThread:47760 [wandb_run.py:_footer_sync_info():3428] logging synced files
2023-11-05 13:38:47,534 INFO    MainThread:47760 [wandb_init.py:init():596] starting backend
2023-11-05 13:38:47,534 INFO    MainThread:47760 [wandb_init.py:init():600] setting up manager
2023-11-05 13:38:47,536 INFO    MainThread:47760 [backend.py:_multiprocessing_setup():106] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2023-11-05 13:38:47,536 INFO    MainThread:47760 [wandb_init.py:init():606] backend started and connected
2023-11-05 13:38:47,550 INFO    MainThread:47760 [wandb_run.py:_label_probe_notebook():1238] probe notebook
2023-11-05 13:38:47,550 INFO    MainThread:47760 [wandb_run.py:_label_probe_notebook():1248] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2023-11-05 13:38:47,550 INFO    MainThread:47760 [wandb_init.py:init():700] updated telemetry
2023-11-05 13:38:47,572 INFO    MainThread:47760 [wandb_init.py:init():737] communicating run to backend with 60.0 second timeout
2023-11-05 13:38:49,064 INFO    MainThread:47760 [wandb_run.py:_on_init():2177] communicating current version
2023-11-05 13:38:49,161 INFO    MainThread:47760 [wandb_run.py:_on_init():2186] got version response upgrade_message: "wandb version 0.15.12 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2023-11-05 13:38:49,162 INFO    MainThread:47760 [wandb_init.py:init():787] starting run threads in backend
2023-11-05 13:38:54,774 INFO    MainThread:47760 [wandb_run.py:_console_start():2158] atexit reg
2023-11-05 13:38:54,774 INFO    MainThread:47760 [wandb_run.py:_redirect():2013] redirect: SettingsConsole.WRAP_RAW
2023-11-05 13:38:54,774 INFO    MainThread:47760 [wandb_run.py:_redirect():2078] Wrapping output streams.
2023-11-05 13:38:54,774 INFO    MainThread:47760 [wandb_run.py:_redirect():2103] Redirects installed.
2023-11-05 13:38:54,775 INFO    MainThread:47760 [wandb_init.py:init():829] run started, returning control to user process
2023-11-05 13:38:54,776 INFO    MainThread:47760 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-11-05 13:38:54,776 INFO    MainThread:47760 [wandb_init.py:_pause_backend():418] pausing backend
2023-11-05 13:38:54,833 INFO    MainThread:47760 [wandb_init.py:_resume_backend():423] resuming backend
2023-11-05 13:38:54,834 INFO    MainThread:47760 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-11-05 13:38:54,834 INFO    MainThread:47760 [wandb_init.py:_pause_backend():418] pausing backend
2023-11-05 13:38:54,861 INFO    MainThread:47760 [wandb_init.py:_resume_backend():423] resuming backend
2023-11-05 13:38:54,966 INFO    MainThread:47760 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-11-05 13:38:54,966 INFO    MainThread:47760 [wandb_init.py:_pause_backend():418] pausing backend
2023-11-05 13:39:31,191 INFO    MainThread:47760 [wandb_init.py:_resume_backend():423] resuming backend
2023-11-05 13:39:31,193 INFO    MainThread:47760 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-11-05 13:39:31,193 INFO    MainThread:47760 [wandb_init.py:_pause_backend():418] pausing backend
2023-11-05 13:39:31,265 INFO    MainThread:47760 [wandb_init.py:_resume_backend():423] resuming backend
2023-11-05 13:39:31,266 INFO    MainThread:47760 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-11-05 13:39:31,267 INFO    MainThread:47760 [wandb_init.py:_pause_backend():418] pausing backend
2023-11-05 13:39:31,328 INFO    MainThread:47760 [wandb_init.py:_resume_backend():423] resuming backend
2023-11-05 13:39:31,372 INFO    MainThread:47760 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-11-05 13:39:31,372 INFO    MainThread:47760 [wandb_init.py:_pause_backend():418] pausing backend
2023-11-05 13:39:31,400 INFO    MainThread:47760 [wandb_init.py:_resume_backend():423] resuming backend
2023-11-05 13:39:33,368 INFO    MainThread:47760 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-11-05 13:39:33,369 INFO    MainThread:47760 [wandb_init.py:_pause_backend():418] pausing backend
2023-11-05 13:39:33,393 INFO    MainThread:47760 [wandb_init.py:_resume_backend():423] resuming backend
2023-11-05 13:39:33,407 INFO    MainThread:47760 [wandb_setup.py:_flush():76] Current SDK version is 0.15.2
2023-11-05 13:39:33,407 INFO    MainThread:47760 [wandb_setup.py:_flush():76] Configure stats pid to 47760
2023-11-05 13:39:33,407 INFO    MainThread:47760 [wandb_setup.py:_flush():76] Loading settings from /Users/josepsmachine/.config/wandb/settings
2023-11-05 13:39:33,408 INFO    MainThread:47760 [wandb_setup.py:_flush():76] Loading settings from /Users/josepsmachine/Documents/PROGRAMMING/BioBytes_Uib_Datathon2023/wandb/settings
2023-11-05 13:39:33,408 INFO    MainThread:47760 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-11-05 13:39:33,408 INFO    MainThread:47760 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-11-05 13:39:33,408 INFO    MainThread:47760 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-11-05 13:39:33,408 INFO    MainThread:47760 [wandb_init.py:_log_setup():507] Logging user logs to /Users/josepsmachine/Documents/PROGRAMMING/BioBytes_Uib_Datathon2023/wandb/run-20231105_133933-26pho1ks/logs/debug.log
2023-11-05 13:39:33,408 INFO    MainThread:47760 [wandb_init.py:_log_setup():508] Logging internal logs to /Users/josepsmachine/Documents/PROGRAMMING/BioBytes_Uib_Datathon2023/wandb/run-20231105_133933-26pho1ks/logs/debug-internal.log
2023-11-05 13:39:33,408 INFO    MainThread:47760 [wandb_init.py:init():547] calling init triggers
2023-11-05 13:39:33,408 INFO    MainThread:47760 [wandb_init.py:init():554] wandb.init called with sweep_config: {}
config: {}
2023-11-05 13:39:33,408 INFO    MainThread:47760 [wandb_init.py:init():571] re-initializing run, found existing run on stack: wimtjzb1
2023-11-05 13:39:33,411 INFO    MainThread:47760 [wandb_run.py:_finish():1893] finishing run haradai/datahon_uib_2023/wimtjzb1
2023-11-05 13:39:33,411 INFO    MainThread:47760 [jupyter.py:save_history():445] not saving jupyter history
2023-11-05 13:39:33,411 INFO    MainThread:47760 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2023-11-05 13:39:33,411 INFO    MainThread:47760 [wandb_init.py:_jupyter_teardown():435] cleaning up jupyter logic
2023-11-05 13:39:33,412 INFO    MainThread:47760 [wandb_run.py:_atexit_cleanup():2127] got exitcode: 0
2023-11-05 13:39:33,412 INFO    MainThread:47760 [wandb_run.py:_restore():2110] restore
2023-11-05 13:39:33,412 INFO    MainThread:47760 [wandb_run.py:_restore():2116] restore done
